name: conventionalcommits-semantic-releasing
description: Semantic Release Action using Conventional Commits
author: Martina Baiardi

inputs:
  token:
    description: 'Personal Access token with push permissions on repository'
    required: true
  test:
    description: 'A test param'
    required: true
    default: 'testing-default' 

runs:
    using: composite
    steps:
      - run: echo ${{ inputs.test }}
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
        with:
          token: ${{ inputs.token }}

      - name: Install npm package
        run: npm install

      - name: Release
        env: 
          GITHUB_TOKEN: ${{ inputs.token }}
        run: npx semantic-release  
branding:
  icon: 'tag'
  color: 'green'
          
